"""Простой статический билдер для docs-toolkit/docs/.

Преобразует все .md в HTML, добавляет общую навигацию и стили.
Без зависимостей: использует docstoolkit.serve._md_to_html().

Запуск:
    cd docs-toolkit/docs
    python build.py             # → ./build/
    python build.py --serve     # build + локальный preview
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT.parent))

from docstoolkit.serve import _md_to_html, _escape

OUTPUT_DIR = ROOT / "build"

CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       max-width: 960px; margin: 2em auto; padding: 0 1em; line-height: 1.6;
       color: #24292e; }
h1, h2, h3 { color: #0366d6; border-bottom: 1px solid #eee; padding-bottom: 0.3em; }
a { color: #0366d6; text-decoration: none; }
a:hover { text-decoration: underline; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th, td { border: 1px solid #e1e4e8; padding: 8px 12px; text-align: left; }
th { background: #f6f8fa; }
code { background: #f6f8fa; padding: 2px 6px; border-radius: 3px;
       font-family: "SF Mono", Consolas, monospace; font-size: 0.9em; }
pre { background: #f6f8fa; padding: 12px; border-radius: 6px; overflow: auto; }
nav { background: #f6f8fa; padding: 12px 16px; border-radius: 6px; margin: 1em 0; }
nav a { margin-right: 1em; font-weight: 500; }
.footer { color: #586069; font-size: 0.85em; text-align: center;
          margin-top: 3em; padding-top: 1em; border-top: 1px solid #eee; }
"""

NAV_ITEMS = [
    ("index.html", "🏠 Home"),
    ("installation.html", "📦 Installation"),
    ("rag.html", "🤖 RAG"),
    ("plugins.html", "🔌 Plugins"),
]


def render_page(title: str, body_md: str) -> str:
    nav = '<nav>' + ' '.join(f'<a href="{href}">{label}</a>' for href, label in NAV_ITEMS) + '</nav>'
    body_html = _md_to_html(body_md)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_escape(title)} — docs-toolkit</title>
<style>{CSS}</style>
</head>
<body>
{nav}
{body_html}
<div class="footer">Generated by docs-toolkit/docs/build.py</div>
</body>
</html>"""


def build():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    md_files = sorted(ROOT.glob("*.md"))
    print(f"Building {len(md_files)} pages → {OUTPUT_DIR}/")
    for md in md_files:
        text = md.read_text(encoding="utf-8")
        # Title из первого H1
        title = md.stem
        for line in text.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
        # Меняем .md ссылки на .html для intra-portal navigation
        body = text
        import re
        body = re.sub(r'\(([^)]+)\.md\)', r'(\1.html)', body)
        html = render_page(title, body)
        out = OUTPUT_DIR / f"{md.stem}.html"
        out.write_text(html, encoding="utf-8")
        print(f"  {md.name} → {out.name}")
    print(f"\n✅ Done. Open {OUTPUT_DIR}/index.html")


def serve(port: int = 8001):
    import http.server
    import socketserver
    import os
    os.chdir(OUTPUT_DIR)
    handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", port), handler) as httpd:
        httpd.allow_reuse_address = True
        print(f"📡 Serving http://localhost:{port}/")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    build()
    if "--serve" in sys.argv:
        serve()
